### ISSUE TITLE
make fails

### ISSUE THREAD

**Issue by garvankeeley** [crankycoder/DemoStumbler#2]
$ make
./gradlew build

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugCompile'.
   > Could not find com.crankycoder:stumbler:0.9.0.
     Searched in the following locations:
         https://jcenter.bintray.com/com/crankycoder/stumbler/0.9.0/stumbler-0.9.0.pom
         https://jcenter.bintray.com/com/crankycoder/stumbler/0.9.0/stumbler-0.9.0.jar
         http://dl.bintray.com/crankycoder/libMozStumbler/com/crankycoder/stumbler/0.9.0/stumbler-0.9.0.pom
         http://dl.bintray.com/crankycoder/libMozStumbler/com/crankycoder/stumbler/0.9.0/stumbler-0.9.0.jar
         file:/Users/gkeeley/ADT_SDK/extras/android/m2repository/com/crankycoder/stumbler/0.9.0/stumbler-0.9.0.pom
         file:/Users/gkeeley/ADT_SDK/extras/android/m2repository/com/crankycoder/stumbler/0.9.0/stumbler-0.9.0.jar
         file:/Users/gkeeley/ADT_SDK/extras/google/m2repository/com/crankycoder/stumbler/0.9.0/stumbler-0.9.0.pom
         file:/Users/gkeeley/ADT_SDK/extras/google/m2repository/com/crankycoder/stumbler/0.9.0/stumbler-0.9.0.jar
     Required by:
         DemoStumbler:app:unspecified

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

**Comment by crankycoder** [comment]
Sorry I was tweaking the entry in bintray trying to push into jcenter. I'll try doing that again without changing the groupname from 'com.crankycoder' to 'mozilla' until the jcenter maven repo can be used.
